name: Pregeneration Test

on:
  push:
    branches:
      - '*'
      - '!generate/aws-lc-*'
  pull_request:
    branches:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  # We can pin the version if nightly is too unstable.
  # Otherwise, we test against the latest version.
  RUST_NIGHTLY_TOOLCHAIN: nightly
  RUST_SCRIPT_NIGHTLY_TOOLCHAIN: nightly-2024-05-22
  GOPROXY: https://proxy.golang.org,direct
jobs:
  sys-bindings:
    if: github.repository_owner == 'aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          # Our aws-lc-sys generation scripts require nightly.
          toolchain: ${{ env.RUST_SCRIPT_NIGHTLY_TOOLCHAIN }}
      - run: rustup override set $RUST_NIGHTLY_TOOLCHAIN
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: rust-script
      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install cmake gcc clang golang
      - name: Regenerate aws-lc-sys crate
        working-directory: ./aws-lc-sys
        run: |
          rm -rf symbols/*
          rm -rf generated-include/openssl/*
          ../scripts/generate/_collect_symbols_build.sh -c aws-lc-sys
          ../scripts/generate/_generate_prefix_headers.sh -c aws-lc-sys
          ../scripts/generate/_generate_bindings.sh -c aws-lc-sys
      - name: aws-lc-sys build
        working-directory: ./aws-lc-sys
        run: |
          cargo build
      - name: aws-lc-sys test
        working-directory: ./aws-lc-sys
        run: |
          cargo test
      - name: aws-lc-sys packaging
        working-directory: ./aws-lc-sys
        run: |
          cargo package --allow-dirty
      - name: aws-lc-rs build
        working-directory: ./aws-lc-rs
        run: |
          cargo build
      - name: aws-lc-rs test
        working-directory: ./aws-lc-rs
        run: |
          cargo test
  fips-sys-bindings:
    if: github.repository_owner == 'aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          # Our aws-lc-fips-sys generation scripts require nightly.
          toolchain: ${{ env.RUST_SCRIPT_NIGHTLY_TOOLCHAIN }}
      - run: rustup override set $RUST_NIGHTLY_TOOLCHAIN
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: rust-script
      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install cmake gcc clang golang
      - name: Regenerate aws-lc-fips-sys crate
        working-directory: ./aws-lc-fips-sys
        run: |
          rm -rf symbols/*
          rm -rf generated-include/openssl/*
          ../scripts/generate/_collect_symbols_build.sh -c aws-lc-fips-sys -f
          ../scripts/generate/_generate_prefix_headers.sh -c aws-lc-fips-sys -f
          ../scripts/generate/_generate_bindings.sh -c aws-lc-fips-sys
      - name: aws-lc-fips-sys build
        working-directory: ./aws-lc-fips-sys
        run: |
          cargo build
      - name: aws-lc-fips-sys test
        working-directory: ./aws-lc-fips-sys
        run: |
          cargo test
      - name: aws-lc-fips-sys packaging
        working-directory: ./aws-lc-fips-sys
        run: |
          cargo package --allow-dirty
      - name: aws-lc-rs build
        working-directory: ./aws-lc-rs
        run: |
          cargo build --no-default-features --features=fips
      - name: aws-lc-rs test
        working-directory: ./aws-lc-rs
        run: |
          cargo test --no-default-features --features=fips
